# Generated by Django 4.2.7 on 2023-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='estado',
            field=models.CharField(choices=[('HABILITADA', 'habilitada'), ('DESHABILITADA', 'deshabilitada')], default='HABILITADA', max_length=20),
        ),
    ]
