# Generated by Django 4.2.7 on 2023-11-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_detalle_boleta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_factura',
            name='estado',
            field=models.CharField(choices=[('HABILITADA', 'habilitada'), ('DESHABILITADA', 'deshabilitada')], default='HABILITADA', max_length=20),
        ),
    ]
