# Generated by Django 5.0 on 2023-12-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_boleta_detalle_boleta2'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
