# Generated by Django 5.0 on 2023-12-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_factura_detalle_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_factura',
            name='proveedor',
        ),
    ]
