# Generated by Django 5.0 on 2023-12-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0006_remove_detalle_factura_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.CharField(max_length=50),
        ),
    ]
